# Generated by Django 3.2.5 on 2021-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('validity', models.IntegerField()),
            ],
        ),
    ]
