# Generated by Django 3.2.5 on 2021-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0006_auto_20210721_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sum_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
