# Generated by Django 3.2.5 on 2021-07-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0007_item_sum_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sum_value1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
