# Generated by Django 3.2.5 on 2021-07-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0008_item_sum_value1'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='end_validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
