# Generated by Django 3.2.5 on 2021-07-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0009_contrato_end_validity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('end_validity', models.DateField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juridico.contrato')),
            ],
        ),
    ]
