# Generated by Django 3.2.5 on 2021-08-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0010_aditivoprazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
