# Generated by Django 3.2.5 on 2021-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0011_alter_contrato_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='official_diary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
