# Generated by Django 3.2.5 on 2021-08-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0012_contrato_official_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivoprazo',
            name='official_diary',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
