# Generated by Django 3.2.5 on 2021-08-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0013_aditivoprazo_official_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditivoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('validity', models.IntegerField(blank=True, null=True)),
                ('end_validity', models.DateField(blank=True, null=True)),
                ('official_diary', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage', models.CharField(choices=[(1, '1%'), (2, '2%'), (3, '3%'), (4, '4%'), (5, '5%'), (6, '6%'), (7, '7%'), (8, '8%'), (9, '9%'), (10, '10%'), (11, '11%'), (12, '12%'), (13, '13%'), (14, '14%'), (15, '15%'), (16, '16%'), (17, '17%'), (18, '18%'), (19, '19%'), (20, '20%'), (21, '21%'), (22, '22%'), (23, '23%'), (24, '24%'), (25, '25%')], max_length=50)),
                ('aditivo_value', models.FloatField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juridico.contrato')),
            ],
        ),
    ]
