# Generated by Django 3.2.5 on 2021-08-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0019_alter_aditivovalor_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pos_aditivo_value',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='remove_sum',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
