# Generated by Django 3.2.5 on 2021-08-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0020_auto_20210808_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='identity_aditivo_valor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
