# Generated by Django 3.2.5 on 2021-08-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0021_item_identity_aditivo_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aditivovalor',
            name='difference',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
