# Generated by Django 3.2.5 on 2021-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0022_aditivovalor_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
