# Generated by Django 3.2.5 on 2021-08-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0024_supressao'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='identity_supressao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pos_supressao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
